name: Github Upload
description: Upload assets to Github with ease.

branding:
  icon: upload
  color: green

inputs:
  file:
    description: File to upload.
    required: false
    example: distribution.zip
  name:
    description: Name of uploaded file.
    required: false
    example: distribution-${TAG}.zip
  label:
    description: Label of the uploaded file.
    required: false
    exammple: Complete distribution (zip)
  type:
    description: Content type of the uploaded file.
    required: false
    example: application/zip

  files:
    description: An expression to indicate files to upload.
    required: false
    example: dist/*

  script:
    description: Script performing uploads.
    required: false
    example: |
      upload -f distribution.zip

  script_path:
    description: Path to a script performing uploads.
    required: false
    example: .github/uploads.sh

runs:
  using: docker
  image: 'docker://[REPO]:[VERSION]'
